content/using_bookwyrm/instances.md
I added my instance to the instance list for ease of discoverability.
=> Adds bookclub.techstartups.space to instance list.

.gitignore, content/contributing/contributing.md
i also added a gitignore that ignores __pycache__ and generated output, idk if this is something you want, but i figured it might be useful : )
=> fix translation instructions link

content/using_bookwyrm/instances.md
Super-trivial, but just for consistency and to encourage good web hygiene. Thanks for putting this together, I’ve wanted something like this for a while!
=> http —> https

content/running_bookwyrm/optional_features.md
This PR goes with the Preview Images feature: https://github.com/bookwyrm-social/bookwyrm/pull/1142
=> Running BookWyrm > Optional Features > Preview Images

content/running_bookwyrm/external-storage.md, content/running_bookwyrm/install-prod.md
This doc goes with this PR on the Bookwyrm app repo: https://github.com/bookwyrm-social/bookwyrm/pull/1163
=> External storage documentation

.github/workflows/deploy.yml
=> Adds deployment flow

content/running_bookwyrm/cli.md
Some headers were not displaying properly. Now they are.
Resolves #41
=> fix command formatting

content/running_bookwyrm/install-prod.md
Fixes bookwyrm-social/bookwyrm#1641
=> add instructions for renewing HTTPS certs

content/contributing/install-dev.md, content/running_bookwyrm/cli.md, content/running_bookwyrm/install-prod.md
Related to: https://github.com/bookwyrm-social/bookwyrm/pull/1949
=> Updates install instructions

content/contributing/style_guide.md, content/using-bookwyrm/posting-statuses.md
- add closing parenthesis and comma to style_guide.md
- add posting_statuses.md
This is not at all comprehensive, just thought it would be nice to start on this.
=> Start a "Using BookWyrm" section

content/running_bookwyrm/install-prod.md, site/install-prod.html
=> Fixes link to reverse proxy documentation

content/running_bookwyrm/cli.md, content/running_bookwyrm/external-storage.md, content/running_bookwyrm/monitoring-queue.md, content/running_bookwyrm/optional_features.md
Fixes #79 
I'm not sure, whether I get too technical or whether all tasks should be documented and explained.
So for now, I resorted to point to the codebase for easier study.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>
=> Document Celery and Flower services

content/running_bookwyrm/cli.md, content/running_bookwyrm/external-storage.md, content/running_bookwyrm/install-prod-dockerless.md, content/running_bookwyrm/updating.md
The docs changes for bookwyrm-social/bookwyrm#2527
=> Add docs when to run new compile_themes management command

content/running_bookwyrm/cli.md, content/running_bookwyrm/optional_features.md
As seen on https://github.com/bookwyrm-social/bookwyrm/pull/2522
=> Add info about remove_remote_user_preview_images command

content/codebase/activitypub.md
Was just poking around documentation and noticed this, hope you don't mind the nit PR 🙏 
Very cool to find someone playing around with federated books!
=> Fix typo and consistency in activitypub.md

.github/workflows/black.yml, requirements.txt
Same as bookwyrm-social/bookwyrm#2645
=> Upgrade and pin black to 22.12.0

content/contributing/install-dev.md
Link is broken on the Developer Environment page.
=> Broken link to command line tool on the Developer Environment page

generate.py, requirements.txt, templates/layout.html
Code syntax highlighting wasn't working.
This should fix that.
=> fix syntax highlighting

.github/workflows/deploy.yml
update to github action:
- installs dependencies
- processes translations
- compiles site
- THEN deploys code to server
=> compile and deploy site on push to main

content/running_bookwyrm/install-prod.md
Related to: https://github.com/bookwyrm-social/bookwyrm/issues/3148
=> Fixes references to uncommenting lines in nginx config

generate.py, i18n.py, plugins/add_header_links.py, templates/layout.html
Also update formatting of a couple of files with "black".
fixes #134
=> Link directy to source in "Contribute to this page" link

.github/workflows/deploy.yml
=> use matrix to deploy different versions

.github/workflows/deploy.yml
=> clean up old versions code

content/running_bookwyrm/management-commands.md
=> Document show_duplicate_authors admin command

content/reference/_meta.yml, content/reference/cli.md, content/reference/environment.md
* add references section
* move CLI to references
* add reference page for ENV values
=> add references section and env values

content/reference/environment.md, content/running_bookwyrm/optional_features.md, content/using_bookwyrm/posting-statuses.md, content/using_bookwyrm/user-migration.md
Adds explanation of spoiler warnings and star ratings. Most pages are titled where Most Words are Capitalised so I added capital letters to 4 pages.
Please read over my changes to ensure it makes sense and has no errors before merging.
Also: do you think any other status component should be explained, like Quote?
=> Add: spoiler alerts, star ratings. Capitalise page titles

site/static/css/bookwyrm.css, site/static/js/bookwyrm.js, templates/layout.html
- adds hamburger to show/hide nav bar and menu on small screens
- hides menu on smaller screens
- moves JS into separate file
- moves menu to side of screen allowing more room for content
- fixes #168
=> make menu and nav bar responsive

i18n.py
=> fix filepath check for l18n

generate.py, site/static/css/bookwyrm.css, site/static/js/bookwyrm.js, templates/layout.html
- align to new design
- clean up js file comments
- update "development" version language
- fix logic for showing dev banner etc
=> fix layout in v0.7.5 docs

site/static/js/bookwyrm.js
Sorry, mucked up the last pull
=> actually commit js file... (to v0.7.5)

site/static/js/bookwyrm.js, templates/layout.html
Just some cleanup to fix the version toggle - this doesn't really matter on `development` but will break future versions if not updated.
=> Fix versions logic and clean up JS file

content/reference/environment.md, content/running_bookwyrm/external-storage.md
Fixes #207
Fixes #211
Fixes #212
Fixes #213
Fixes #214
Fixes #215
=> Update env info
